name: CI Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
      - run: npm run build-all
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v3
        name: Upload Windows Installer
        with:
          name: twinkle-tray-exe-${{ github.ref_name }}-${{ github.sha }}
          path: dist/*.exe
      - uses: actions/upload-artifact@v3
        name: Upload x64 AppX
        with:
          name: twinkle-tray-appx-x64-${{ github.ref_name }}-${{ github.sha }}
          path: dist/*-store.appx
      - uses: actions/upload-artifact@v3
        name: Upload ARM64 AppX
        with:
          name: twinkle-tray-appx-arm64-${{ github.ref_name }}-${{ github.sha }}
          path: dist/*-store-arm64.appx