name: CI Build

on: [push, pull_request]

jobs:
  win32:
    name: "Build Win32 Installer"
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
      - run: npm ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run parcel-build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm exec electron-builder -- --x64 --config.extraMetadata.version="${{ steps.info.outputs.version }}+${{ github.sha }}" --config.buildVersion="${{ steps.info.outputs.version }}+${{ github.sha }}" --config.win.artifactName="Twinkle Tray v${{ steps.info.outputs.version }}.exe"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        name: Upload Windows Installer
        with:
          name: twinkle-tray-exe-${{ github.ref_name }}-${{ github.sha }}
          path: dist/*.exe
  appx:
    name: "Build AppX Packages"
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: package.json info
        id: info
        uses: jaywcjlove/github-action-package@main
      - run: npm ci
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run appx
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        name: Upload x64 AppX
        with:
          name: twinkle-tray-appx-x64-${{ github.ref_name }}-${{ github.sha }}
          path: dist/*-store.appx
      - run: npm run appx-arm64
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        name: Upload ARM64 AppX
        with:
          name: twinkle-tray-appx-arm64-${{ github.ref_name }}-${{ github.sha }}
          path: dist/*-store-arm64.appx